#ifndef __VERSION_H__
#define __VERSION_H__

/*
 *	BuildAll may pass ELASTICDRIVERVERSION, ELASTIC_RESOURCE_VERSION
 *	and ES_DRVFILE_VERSION via winbuild/elasticodbc.vcxproj.
 */
#ifdef ES_ODBC_VERSION

#ifndef ELASTICSEARCHDRIVERVERSION
#define ELASTICSEARCHDRIVERVERSION ES_ODBC_VERSION
#endif
#ifndef ELASTICSEARCH_RESOURCE_VERSION
#define ELASTICSEARCH_RESOURCE_VERSION ELASTICSEARCHDRIVERVERSION
#endif
#ifndef ES_DRVFILE_VERSION
#define ES_DRVFILE_VERSION ES_ODBC_DRVFILE_VERSION
#endif

#endif  // ES_ODBC_VERSION

#endif
