name: Open Distro for Elasticsearch ODBC Driver

on: [push, pull_request]

jobs:    
  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: sql-odbc
    steps:
    - uses: actions/checkout@v1
    - name: run-cppcheck
      run: |
        brew install cppcheck
        sh run_cppcheck.sh
    - name: upload-cppcheck-results
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: cppcheck-results
        path: sql-odbc/cppcheck-results.log
    - name: get-dependencies
      run: |
        brew unlink unixodbc
        brew install curl
        brew install cmake
        brew install libiodbc
    - name: aws-sdk-cpp-setup
      run: |
        sh aws_sdk_cpp_setup.sh
    - name: configure
      run: |
        prefix_path=$(pwd)
        mkdir cmake-build
        cd cmake-build
        cmake ../src -DCMAKE_INSTALL_PREFIX=$prefix_path/AWSSDK/ -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="core" -DCUSTOM_MEMORY_MANAGEMENT="OFF" -DENABLE_RTTI="OFF" -DENABLE_TESTING="OFF"
        cd ..
    - name: build-driver
      run: |
        cmake --build cmake-build
    #- name: test
    #  run: | 
    #    bash ./run_test_runner.sh
    - name: build-installer
      if: success()
      run: |
        cd cmake-build
        cmake ../src 
        make
        cpack .
        cd ..
    - name: create-output
      if: success()
      run: |
        mkdir build
        mkdir test-output
        mkdir installer
        cp ./lib64/*.dylib build
        cp ./lib64/*.a build
        cp $(ls -d bin64/* | grep -v "\.") build
        cp ./cmake-build/*.pkg installer
    #    cp ./bin64/*.html test-output
    #    cp ./bin64/*.log test-output
    - name: upload-build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: mac64-build
        path: sql-odbc/build
    - name: upload-installer
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: mac64-installer
        path: sql-odbc/installer
    #- name: upload-test-results
    #  if: success()
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: mac-test-results
    #    path: test-output
  build-windows32:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: sql-odbc
    steps:
    - uses: actions/checkout@v1
    - name: add-msbuild-to-path
      uses: microsoft/setup-msbuild@v1.0.0
    - name: configure-and-build-driver
      run: |
        .\build_win_release32.ps1
    - name: build-installer
      if: success()
      run: |
        $prefix_path = (pwd).path
        cd cmake-build32
        cmake ..\\src -D CMAKE_INSTALL_PREFIX=$prefix_path\AWSSDK\bin -D BUILD_WITH_TESTS=OFF
        msbuild .\PACKAGE.vcxproj -p:Configuration=Release
        cd ..
    #- name: test
    #  run: |
    #    cp .\\libraries\\VisualLeakDetector\\bin32\\*.* .\\bin32\\Release
    #    cp .\\libraries\\VisualLeakDetector\\lib32\\*.lib .\\lib32\\Release
    #    .\run_test_runner.bat
    - name: create-output
      if: always()
      run: |
        mkdir build
        mkdir test-output
        mkdir installer
        cp .\\bin32\\Release\\*.dll build
        cp .\\bin32\\Release\\*.exe build
        cp .\\lib32\\Release\\*.lib build
        cp .\\cmake-build32\\*.msi installer
    #    cp .\\bin32\\Release\\*.log test-output
    #    cp .\\bin32\\Release\\*.html test-output
    - name: upload-build
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: windows32-build
        path: sql-odbc/build
    - name: upload-installer
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: windows32-installer
        path: sql-odbc/installer
    #- name: upload-test-results
    #  if: always()
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: windows-test-results
    #    path: test-output
  build-windows64:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: sql-odbc
    steps:
    - uses: actions/checkout@v1
    - name: add-msbuild-to-path
      uses: microsoft/setup-msbuild@v1.0.0
    - name: configure-and-build-driver
      run: |
        .\build_win_release64.ps1
    - name: build-installer
      if: success()
      run: |
        $prefix_path = (pwd).path
        cd cmake-build64
        cmake ..\\src -D CMAKE_INSTALL_PREFIX=$prefix_path\AWSSDK\bin -D BUILD_WITH_TESTS=OFF
        msbuild .\PACKAGE.vcxproj -p:Configuration=Release
        cd ..
    #- name: test
    #  run: |
    #    cp .\\libraries\\VisualLeakDetector\\bin64\\*.* .\\bin64\\Release
    #    cp .\\libraries\\VisualLeakDetector\\lib64\\*.lib .\\lib64\\Release
    #    .\run_test_runner.bat
    - name: create-output
      if: always()
      run: |
        mkdir build
        mkdir test-output
        mkdir installer
        cp .\\bin64\\Release\\*.dll build
        cp .\\bin64\\Release\\*.exe build
        cp .\\lib64\\Release\\*.lib build
        cp .\\cmake-build64\\*.msi installer
    #    cp .\\bin64\\Release\\*.log test-output
    #    cp .\\bin64\\Release\\*.html test-output
    - name: upload-build
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: windows64-build
        path: sql-odbc/build
    - name: upload-installer
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: windows64-installer
        path: sql-odbc/installer
    #- name: upload-test-results
    #  if: always()
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: windows-test-results
    #    path: test-output
