name: Build and Release SQL-JDBC
# This workflow is triggered on creating tags to master or an opendistro release branch
on:
  push:
    tags:
      - "v*"

jobs:
  Release-SQL-JDBC:
    strategy:
      matrix:
        java: [10]

    name: Build and Release JDBC Plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sql-jdbc

    steps:
      - name: Checkout SQL-JDBC
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew publishShadowPublicationToInternal-releasesRepository '-Dorg.gradle.jvmargs=--add-modules java.xml.bind' -Dbuild.snapshot=false

      - name: Configure Staging AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Publish to S3
        shell: bash
        run: |
          jar=`ls -1t build/libs/*.jar | grep -v "SNAPSHOT.jar" | grep -v "sources.jar" | head -1`

          # Inject the build number before the suffix
          jar_outfile=`basename ${jar%.jar}-build-${GITHUB_RUN_NUMBER}.jar`

          s3_prefix="s3://staging.artifacts.opendistroforelasticsearch.amazon.com/snapshots/elasticsearch-clients/sql-jdbc/"

          echo "Copying ${jar} to ${s3_prefix}${jar_outfile}"
          aws s3 cp --quiet $jar ${s3_prefix}${jar_outfile}
